spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: book-service
              uri: lb://books-service
              predicates:
                - Path=/v1/book/**
            - id: library-service
              uri: lb://library-service
              predicates:
                - Path=/v1/library/**
          discover:
            locator:
              enabled: true

server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info

  